### PR TITLE
[serverless-apollo-contentful] Add missing .env file instructions

### LINKED ISSUE #796: [serverless-apollo-contentful] Add missing .env file instructions

### PR DESCRIPTION
**Pull request by kodejuice**
## Type of change

Add .env instructions

- [x] Documentation change
- [ ] Bug fix

## Checklist

- [ ] These changes follow the [contributing guidelines](https://github.com/thisdot/starter.dev/blob/main/CONTRIBUTING.md)
- [ ] This starter kit has been approved by the maintainers
- [ ] Changes for this new starter kit are being pushed to an integration branch instead of main
- [ ] All dependencies are version locked
- [x] This fix resolves #796 
- [ ] I have verified the fix works and introduces no further errors

### CODE REVIEW

**Review by iansamz — APPROVED** [review]
LGTM but we can also screenshots

**Comment by kodejuice** [comment]
> LGTM but we can also screenshots

:thinking: screenshots of the contentful page?, wouldn't that look weird inside of the README

**Review by iansamz — CHANGES_REQUESTED** [review]
Please add image to and proper description to get the keys.
i.e heading to settings then selecting API keys. and which keys to select

**Review by mbicknese — CHANGES_REQUESTED** [review]
Looking good so far, when trying to run these steps we were missing which fields need to go into the models. Can you add the details for the fields?

**Review by mbicknese — APPROVED** [review]

**Review by iansamz — APPROVED** [review]

**Pull request merged**
