### PR TITLE
feat: [sveltekit-pod] Generate project and establish integration point

### LINKED ISSUE #377: [sveltekit-pod] 0. Generate project and establish integration point
# Background
To make tasks parallelizable, we should create kits via integration branches to make PRs smaller and easier to read while not breaking the upstream build. Integration branches may be cleaner and easier to implement in isolation as kits are isolated to their own directory anyway.

# Acceptance
- [ ] Generate new project in the `starters/` creating a name that includes 'framework-store-style' format
- [ ] Find the title in the `<head>` of the public facing index.html (this depends from framework, but usually found in "src/public" folder) and change it to "framework-store-style starter kit"
- [ ] Change the name and description in the package.json
- [ ] Merge change into an integration branch

### PR DESCRIPTION
**Pull request by ihardz**
Resolves #377 

> **Background**
> To make tasks parallelizable, we should create kits via integration branches to make PRs smaller and easier to read while not breaking the upstream build. Integration branches may be cleaner and easier to implement in isolation as kits are isolated to their own directory anyway.
> 
> **Acceptance**
> 
> -  Generate new project in the starters/ creating a name that includes 'framework-store-style' format
> -  Find the title in the <head> of the public facing index.html (this depends from framework, but usually found in "src/public" folder) and change it to "framework-store-style starter kit"
> -  Change the name and description in the package.json
> -  Merge change into an integration branch

### CODE REVIEW

**Review by iansamz — DISMISSED** [review]
LGTM but not so keen on the 'fetch' added on the title of the pod

**Review by flakolefluk — CHANGES_REQUESTED** [review]
I agree with @iansamz on the fetch part of the name, specially because it's a feature of sveltekit that we'll be using, we can discuss with @Zelig880 on how to make it sound more attractive anyway. (i don't expect it to be a blocker)
I know i talked about using the `demo app` as reference, but i believe for the kit repo we may be fine with just the `skeleton app` to start, and then bring in what we need.

**Comment by Zelig880** [comment]
Agreed on the above, we can move things as we go along and this should not be a blocker for now. :)

**Review by iansamz — APPROVED** [review]
Looks okay just left with setting up the integration branch

**Review by flakolefluk — APPROVED** [review]

**Pull request merged**
