### PR TITLE
fix(#464): hide showcase links for kits with no showcase

### LINKED ISSUE #464: Showcase should be hidden if there isn't a showcase
Image

### PR DESCRIPTION
**Pull request by jnalei**
This PR closes #464 

"View Showcase" links were previously visible on kits that did not have a showcases. 
Links are now properly rendered based on `hasShowcase` value set in each kit's `package.json` file.

In the example picture below, `qwik-tailwind-graphql` kit does not have a showcase so the link does not display.
Screen Shot 2022-10-27 at 10 05 02 PM

### CODE REVIEW

**Review by jdwilkin4 — DISMISSED** [review]
I tested this out locally and everything is working on my end. 
The only thing I think is missing is letting future contributors know that they should add the `hasShowcase` key in the `package.json`. I can see developers forgetting to add that and for ones that have a showcase it won't show without that key set to true. 

I don't know if we want to add something in the readme or a checklist item in a PR template(which we should probably have anyway) but that is something for us to think about in the future. 👍

**Comment by jnalei** [comment]
> I tested this out locally and everything is working on my end. The only thing I think is missing is letting future contributors know that they should add the `hasShowcase` key in the `package.json`. I can see developers forgetting to add that and for ones that have a showcase it won't show without that key set to true.
> 
> I don't know if we want to add something in the readme or a checklist item in a PR template(which we should probably have anyway) but that is something for us to think about in the future. 👍

@jdwilkin4 Yes! Good point and thank you for reminding me! I meant to add a note in the readme then completely forgot about it.. will update in another commit 👍

**Review by jdwilkin4 — APPROVED** [review]
LGTM 👍

**Review by morgnism — APPROVED** [review]
LGTM

**Pull request merged**
