### PR TITLE
Qwik fetch tailwind/344 setup storybook

### LINKED ISSUE #344: [qwik-pod] 2. Setup Storybook
# Background
Storybook is a great way to build, validate, and test components. We want to ship a working storybook instance with each kit.

# Acceptance
- [ ] Install and configure storybook
- [ ] Add a simple example of storybook using the existing components

### PR DESCRIPTION
**Pull request by honzikec**
Closes #344 
- [x] Set up storybook with stories for counter and data fetching components.

> To be merged after [391](https://github.com/thisdot/starter.dev/pull/391)

### CODE REVIEW

**Comment by JiaLiPassion** [comment]
@honzikec , I have a question that what is the relationship between this PR and https://github.com/thisdot/starter.dev/pull/397, it seems they are basically the same contents and also committed to the same folder, `starters/qwik-fetch-tailwind`

**Comment by honzikec** [comment]
> @honzikec , I have a question that what is the relationship between this PR and #397, it seems they are basically the same contents and also committed to the same folder, `starters/qwik-fetch-tailwind`

This PR adds Storybook to the kit. [397](https://github.com/thisdot/starter.dev/pull/397) is based on this branch and adds Tailwind and styling.

**Comment by JiaLiPassion** [comment]
Got it, LGTM.

**Review by JiaLiPassion — APPROVED** [review]
Please rebase and merge!

**Pull request merged**
